name: Lint
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
      - name: Check EditorConfig
        run: npx editorconfig-checker
        shell: bash
      - name: Check TypeScript
        run: npx tsc
        shell: bash
      - name: Run ESLint
        run: npm run lint
        shell: bash
